In [1]:
import pandas as pd
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter

In [11]:
geolocator = Nominatim(user_agent="hello")
geocode = RateLimiter(geolocator.geocode, min_delay_seconds=5)

In [40]:
df = pd.read_csv('Cluj10.csv')
df.head()

,Megye,Telepules,Ev,Osszes,Ortodox,GorogKatolikus,RomaiKatolikus,Reformatus,Evangelikus,Unitarius,...,Adventisa,Muzulman,Evangeliumi,OhituOrtodox,ZsinatPresb,AgostaiEvang,FelekezetenKivuli,Ateista,NemValaszolt,Jehova
0,Cluj,Comuna Apahida,1850,2658,214,2137,68,182,2,0,...,0,0,0,0,0,0,0,0,0,0
1,Cluj,Comuna Apahida,1857,2547,847,1431,62,144,0,3,...,0,0,0,0,0,0,0,0,0,0
2,Cluj,Comuna Apahida,1869,2942,1011,1639,45,131,9,9,...,0,0,0,0,0,0,0,0,0,0
3,Cluj,Comuna Apahida,1880,2926,485,1921,133,231,16,14,...,0,0,0,0,0,0,0,0,0,0
4,Cluj,Comuna Apahida,1890,3471,670,2306,152,220,4,15,...,0,0,0,0,0,0,0,0,0,0

In [41]:
df['Telepules'].unique()

array(['Comuna Apahida', 'Apahida', 'Bodrog', 'Campenesti', 'Corpadea',
       'Dezmir', 'Pata', 'Sannicoara', 'Sub Coasta (Kolozs megye'],
      dtype=object)

In [42]:
telep_df = pd.DataFrame(data={'Telepules': df['Telepules'].unique()})
telep_df['Megye'] = df['Megye'].iloc[0]
telep_df['besttelep'] = telep_df['Telepules'] + ', ' + telep_df['Megye']

In [43]:
telep_df

                  Telepules Megye                       besttelep
0            Comuna Apahida  Cluj            Comuna Apahida, Cluj
1                   Apahida  Cluj                   Apahida, Cluj
2                    Bodrog  Cluj                    Bodrog, Cluj
3                Campenesti  Cluj                Campenesti, Cluj
4                  Corpadea  Cluj                  Corpadea, Cluj
5                    Dezmir  Cluj                    Dezmir, Cluj
6                      Pata  Cluj                      Pata, Cluj
7                Sannicoara  Cluj                Sannicoara, Cluj
8  Sub Coasta (Kolozs megye  Cluj  Sub Coasta (Kolozs megye, Cluj

In [44]:
#telep_df['location'] = telep_df['besttelep'].apply(geocode)
#telep_df['point'] = telep_df['location'].apply(lambda loc: tuple(loc.point) if loc else None)

In [45]:
#telep_df = df.merge(telep_df, on=['Telepules'])

In [46]:
#telep_df["Latitude"]=telep_df["location"].apply(lambda x: x.latitude if x != None else None)
#telep_df["Longitude"]=telep_df["location"].apply(lambda x: x.longitude if x != None else None)

In [47]:
telep_df

                  Telepules Megye                       besttelep
0            Comuna Apahida  Cluj            Comuna Apahida, Cluj
1                   Apahida  Cluj                   Apahida, Cluj
2                    Bodrog  Cluj                    Bodrog, Cluj
3                Campenesti  Cluj                Campenesti, Cluj
4                  Corpadea  Cluj                  Corpadea, Cluj
5                    Dezmir  Cluj                    Dezmir, Cluj
6                      Pata  Cluj                      Pata, Cluj
7                Sannicoara  Cluj                Sannicoara, Cluj
8  Sub Coasta (Kolozs megye  Cluj  Sub Coasta (Kolozs megye, Cluj

In [48]:
import numpy as np
import pandas as pd
import re
geolocator = Nominatim(user_agent="hello")
geocode = RateLimiter(geolocator.geocode, min_delay_seconds=5)
   
def get_location(row):
    address = row['besttelep']
    location = geocode(address)
    if location is None:
        address = re.sub(r'Municipiul','',address)
        address = re.sub(r'Comuna','',address)
        address = re.sub(r'Orasul','',address)
        location = geocode(address)
    row['longitude'] = location.longitude
    row['latitude'] = location.latitude
    print(address)
    return row

geolocated_table = telep_df.apply(get_location, axis=1)

 Apahida, Cluj

RateLimiter caught an error, retrying (0/2 tries). Called with (*('Comuna Apahida, Cluj',), **{}).
Traceback (most recent call last):
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\urllib\request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\http\client.py", line 964, in send
    self.connect()
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\http\client.py", line 1392, in connect
    super().connect()
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\http\client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\socket.py", line 724, in create_connection
    raise err
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\socket.py", line 713, in create_connection
    sock.connect(sa)
OSError: [WinError 10051] A socket operation was attempted to an unreachable network

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\site-packages\geopy\geocoders\base.py", line 355, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\urllib\request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10051] A socket operation was attempted to an unreachable network>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\site-packages\geopy\extra\rate_limiter.py", line 126, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\site-packages\geopy\geocoders\osm.py", line 387, in geocode
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\site-packages\geopy\geocoders\base.py", line 380, in _call_geocoder
    raise GeocoderUnavailable('Service not available')
geopy.exc.GeocoderUnavailable: Service not available

 Apahida, Cluj
Apahida, Cluj
Bodrog, Cluj
Campenesti, Cluj

RateLimiter caught an error, retrying (0/2 tries). Called with (*('Corpadea, Cluj',), **{}).
Traceback (most recent call last):
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\urllib\request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\http\client.py", line 964, in send
    self.connect()
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\http\client.py", line 1392, in connect
    super().connect()
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\http\client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\socket.py", line 724, in create_connection
    raise err
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\socket.py", line 713, in create_connection
    sock.connect(sa)
OSError: [WinError 10051] A socket operation was attempted to an unreachable network

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\site-packages\geopy\geocoders\base.py", line 355, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\urllib\request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10051] A socket operation was attempted to an unreachable network>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\site-packages\geopy\extra\rate_limiter.py", line 126, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\site-packages\geopy\geocoders\osm.py", line 387, in geocode
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\site-packages\geopy\geocoders\base.py", line 380, in _call_geocoder
    raise GeocoderUnavailable('Service not available')
geopy.exc.GeocoderUnavailable: Service not available

Corpadea, Cluj

RateLimiter caught an error, retrying (0/2 tries). Called with (*('Dezmir, Cluj',), **{}).
Traceback (most recent call last):
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\urllib\request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\http\client.py", line 964, in send
    self.connect()
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\http\client.py", line 1392, in connect
    super().connect()
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\http\client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\socket.py", line 724, in create_connection
    raise err
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\socket.py", line 713, in create_connection
    sock.connect(sa)
OSError: [WinError 10051] A socket operation was attempted to an unreachable network

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\site-packages\geopy\geocoders\base.py", line 355, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\urllib\request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10051] A socket operation was attempted to an unreachable network>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\site-packages\geopy\extra\rate_limiter.py", line 126, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\site-packages\geopy\geocoders\osm.py", line 387, in geocode
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\site-packages\geopy\geocoders\base.py", line 380, in _call_geocoder
    raise GeocoderUnavailable('Service not available')
geopy.exc.GeocoderUnavailable: Service not available

Dezmir, Cluj

RateLimiter caught an error, retrying (0/2 tries). Called with (*('Pata, Cluj',), **{}).
Traceback (most recent call last):
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\urllib\request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\http\client.py", line 964, in send
    self.connect()
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\http\client.py", line 1392, in connect
    super().connect()
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\http\client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\socket.py", line 724, in create_connection
    raise err
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\socket.py", line 713, in create_connection
    sock.connect(sa)
OSError: [WinError 10051] A socket operation was attempted to an unreachable network

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\site-packages\geopy\geocoders\base.py", line 355, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\urllib\request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10051] A socket operation was attempted to an unreachable network>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\site-packages\geopy\extra\rate_limiter.py", line 126, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\site-packages\geopy\geocoders\osm.py", line 387, in geocode
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\site-packages\geopy\geocoders\base.py", line 380, in _call_geocoder
    raise GeocoderUnavailable('Service not available')
geopy.exc.GeocoderUnavailable: Service not available

Pata, Cluj
Sannicoara, Cluj

RateLimiter caught an error, retrying (0/2 tries). Called with (*('Sub Coasta (Kolozs megye, Cluj',), **{}).
Traceback (most recent call last):
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\urllib\request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\http\client.py", line 964, in send
    self.connect()
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\http\client.py", line 1392, in connect
    super().connect()
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\http\client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\socket.py", line 724, in create_connection
    raise err
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\socket.py", line 713, in create_connection
    sock.connect(sa)
OSError: [WinError 10051] A socket operation was attempted to an unreachable network

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\site-packages\geopy\geocoders\base.py", line 355, in _call_geocoder
    page = requester(req, timeout=timeout, **kwargs)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\urllib\request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10051] A socket operation was attempted to an unreachable network>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\site-packages\geopy\extra\rate_limiter.py", line 126, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\site-packages\geopy\geocoders\osm.py", line 387, in geocode
    self._call_geocoder(url, timeout=timeout), exactly_one
  File "C:\Users\Zsuzsa\Anaconda3\envs\mokus\lib\site-packages\geopy\geocoders\base.py", line 380, in _call_geocoder
    raise GeocoderUnavailable('Service not available')
geopy.exc.GeocoderUnavailable: Service not available

AttributeError: ("'NoneType' object has no attribute 'longitude'", 'occurred at index 8')

In [ ]:
telep_df = df.merge(geolocated_table, on=['Telepules'])

In [27]:
telep_df

,Megye_x,Telepules,Ev,Osszes,Ortodox,GorogKatolikus,RomaiKatolikus,Reformatus,Evangelikus,Unitarius,...,ZsinatPresb,AgostaiEvang,FelekezetenKivuli,Ateista,NemValaszolt,Jehova,Megye_y,besttelep,longitude,latitude
0,Cluj,Comuna Valea Ierii,1930,912,415,445,24,14,2,4,...,0,0,0,0,0,0,Cluj,"Comuna Valea Ierii, Cluj",23.343803,46.647290
1,Cluj,Comuna Valea Ierii,1992,1172,1070,7,15,10,0,0,...,0,0,0,0,0,0,Cluj,"Comuna Valea Ierii, Cluj",23.343803,46.647290
2,Cluj,Comuna Valea Ierii,2002,1026,932,6,9,8,0,0,...,0,0,0,0,0,0,Cluj,"Comuna Valea Ierii, Cluj",23.343803,46.647290
3,Cluj,Comuna Valea Ierii,2011,888,771,7,8,7,0,0,...,0,0,0,0,0,28,Cluj,"Comuna Valea Ierii, Cluj",23.343803,46.647290
4,Cluj,Valea Ierii,1910,341,58,211,30,28,0,4,...,0,0,0,0,0,0,Cluj,"Valea Ierii, Cluj",23.343803,46.647290
5,Cluj,Valea Ierii,1930,912,415,445,24,14,2,4,...,0,0,0,0,0,0,Cluj,"Valea Ierii, Cluj",23.343803,46.647290
6,Cluj,Valea Ierii,1992,856,779,7,15,10,0,0,...,0,0,0,0,0,0,Cluj,"Valea Ierii, Cluj",23.343803,46.647290
7,Cluj,Valea Ierii,2002,742,669,0,9,8,0,0,...,0,0,0,0,0,0,Cluj,"Valea Ierii, Cluj",23.343803,46.647290
8,Cluj,Cerc,1910,376,297,73,0,6,0,0,...,0,0,0,0,0,0,Cluj,"Cerc, Cluj",23.280966,46.620601
9,Cluj,Cerc,1992,177,173,0,0,0,0,0,...,0,0,0,0,0,0,Cluj,"Cerc, Cluj",23.280966,46.620601
10,Cluj,Cerc,2002,143,137,0,0,0,0,0,...,0,0,0,0,0,0,Cluj,"Cerc, Cluj",23.280966,46.620601
11,Cluj,Plopi,1910,124,123,1,0,0,0,0,...,0,0,0,0,0,0,Cluj,"Plopi, Cluj",23.347640,46.655700
12,Cluj,Plopi,1992,139,118,0,0,0,0,0,...,0,0,0,0,0,0,Cluj,"Plopi, Cluj",23.347640,46.655700
13,Cluj,Plopi,2002,141,126,0,0,0,0,0,...,0,0,0,0,0,0,Cluj,"Plopi, Cluj",23.347640,46.655700

In [28]:
telep_df = telep_df.drop(['Megye_y', 'besttelep'], axis=1)

In [29]:
telep_df

,Megye_x,Telepules,Ev,Osszes,Ortodox,GorogKatolikus,RomaiKatolikus,Reformatus,Evangelikus,Unitarius,...,Evangeliumi,OhituOrtodox,ZsinatPresb,AgostaiEvang,FelekezetenKivuli,Ateista,NemValaszolt,Jehova,longitude,latitude
0,Cluj,Comuna Valea Ierii,1930,912,415,445,24,14,2,4,...,0,0,0,0,0,0,0,0,23.343803,46.647290
1,Cluj,Comuna Valea Ierii,1992,1172,1070,7,15,10,0,0,...,0,0,0,0,0,0,0,0,23.343803,46.647290
2,Cluj,Comuna Valea Ierii,2002,1026,932,6,9,8,0,0,...,0,0,0,0,0,0,0,0,23.343803,46.647290
3,Cluj,Comuna Valea Ierii,2011,888,771,7,8,7,0,0,...,0,0,0,0,0,0,0,28,23.343803,46.647290
4,Cluj,Valea Ierii,1910,341,58,211,30,28,0,4,...,0,0,0,0,0,0,0,0,23.343803,46.647290
5,Cluj,Valea Ierii,1930,912,415,445,24,14,2,4,...,0,0,0,0,0,0,0,0,23.343803,46.647290
6,Cluj,Valea Ierii,1992,856,779,7,15,10,0,0,...,0,0,0,0,0,0,0,0,23.343803,46.647290
7,Cluj,Valea Ierii,2002,742,669,0,9,8,0,0,...,0,0,0,0,0,0,0,0,23.343803,46.647290
8,Cluj,Cerc,1910,376,297,73,0,6,0,0,...,0,0,0,0,0,0,0,0,23.280966,46.620601
9,Cluj,Cerc,1992,177,173,0,0,0,0,0,...,0,0,0,0,0,0,0,0,23.280966,46.620601
10,Cluj,Cerc,2002,143,137,0,0,0,0,0,...,0,0,0,0,0,0,0,0,23.280966,46.620601
11,Cluj,Plopi,1910,124,123,1,0,0,0,0,...,0,0,0,0,0,0,0,0,23.347640,46.655700
12,Cluj,Plopi,1992,139,118,0,0,0,0,0,...,0,0,0,0,0,0,0,0,23.347640,46.655700
13,Cluj,Plopi,2002,141,126,0,0,0,0,0,...,0,0,0,0,0,0,0,0,23.347640,46.655700

In [30]:
telep_df.to_csv(".\proba.csv",index=False)

In [31]:
df = pd.read_csv('proba.csv')
df.head()

,Megye_x,Telepules,Ev,Osszes,Ortodox,GorogKatolikus,RomaiKatolikus,Reformatus,Evangelikus,Unitarius,...,Evangeliumi,OhituOrtodox,ZsinatPresb,AgostaiEvang,FelekezetenKivuli,Ateista,NemValaszolt,Jehova,longitude,latitude
0,Cluj,Comuna Valea Ierii,1930,912,415,445,24,14,2,4,...,0,0,0,0,0,0,0,0,23.343803,46.64729
1,Cluj,Comuna Valea Ierii,1992,1172,1070,7,15,10,0,0,...,0,0,0,0,0,0,0,0,23.343803,46.64729
2,Cluj,Comuna Valea Ierii,2002,1026,932,6,9,8,0,0,...,0,0,0,0,0,0,0,0,23.343803,46.64729
3,Cluj,Comuna Valea Ierii,2011,888,771,7,8,7,0,0,...,0,0,0,0,0,0,0,28,23.343803,46.64729
4,Cluj,Valea Ierii,1910,341,58,211,30,28,0,4,...,0,0,0,0,0,0,0,0,23.343803,46.64729

In [39]:
import os

directory = os.fsencode("./")

for file in os.listdir(directory):
    filename = os.fsdecode(file)
    if filename.endswith(".csv"): 
        print(filename)
        continue
    else:
        continue

Cluj1.csv
Cluj10.csv
Cluj11.csv
Cluj12.csv
Cluj13.csv
Cluj14.csv
Cluj15.csv
Cluj16.csv
Cluj17.csv
Cluj18.csv
Cluj19.csv
Cluj2.csv
Cluj20.csv
Cluj21.csv
Cluj22.csv
Cluj23.csv
Cluj24.csv
Cluj25.csv
Cluj26.csv
Cluj27.csv
Cluj28.csv
Cluj29.csv
Cluj3.csv
Cluj30.csv
Cluj31.csv
Cluj32.csv
Cluj33.csv
Cluj34.csv
Cluj35.csv
Cluj36.csv
Cluj37.csv
Cluj38.csv
Cluj39.csv
Cluj4.csv
Cluj40.csv
Cluj42.csv
Cluj43.csv
Cluj44.csv
Cluj45.csv
Cluj46.csv
Cluj47.csv
Cluj48.csv
Cluj49.csv
Cluj5.csv
Cluj50.csv
Cluj51.csv
Cluj52.csv
Cluj53.csv
Cluj54.csv
Cluj55.csv
Cluj56.csv
Cluj57.csv
Cluj58.csv
Cluj59.csv
Cluj6.csv
Cluj60.csv
Cluj61.csv
Cluj62.csv
Cluj63.csv
Cluj64.csv
Cluj65.csv
Cluj66.csv
Cluj67.csv
Cluj68.csv
Cluj69.csv
Cluj7.csv
Cluj70.csv
Cluj71.csv
Cluj72.csv
Cluj73.csv
Cluj74.csv
Cluj75.csv
Cluj76.csv
Cluj77.csv
Cluj78.csv
Cluj79.csv
Cluj8.csv
Cluj80.csv
Cluj81.csv
Cluj9.csv